[package]
name = "pvss"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent@typed.io>"]
description = "Publicly verifiable secret sharing implementations"
homepage = "https://github.com/vincenthz/rust-pvss"
repository = "https://github.com/vincenthz/rust-pvss"
license-file = "LICENSE"

[lib]
name = "pvss"

[dependencies]
openssl = "0.9.14"
